"""add category to products

Revision ID: 8d8365048014
Revises: 492e2bbd1ca3
Create Date: 2026-07-05 13:43:57.715693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8365048014'
down_revision = '492e2bbd1ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=False))
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
